version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.16
    working_directory: /go/src/github.com/perlogix/dama
    steps:
      - setup_remote_docker
      - run: git clone https://github.com/perlogix/dama.git -b $CIRCLE_BRANCH .
      - run:
          shell: /bin/bash
          command: |
            make buildall
            make certs
            make config
            make docker